# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import messenger_pb2 as messenger__pb2


class MessengerCallerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetMessengerData = channel.unary_unary(
        '/MessengerCaller/GetMessengerData',
        request_serializer=messenger__pb2.MessengerQuery.SerializeToString,
        response_deserializer=messenger__pb2.MessengerResponse.FromString,
        )


class MessengerCallerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetMessengerData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MessengerCallerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetMessengerData': grpc.unary_unary_rpc_method_handler(
          servicer.GetMessengerData,
          request_deserializer=messenger__pb2.MessengerQuery.FromString,
          response_serializer=messenger__pb2.MessengerResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MessengerCaller', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
