# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messenger.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messenger.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0fmessenger.proto\"\x1f\n\x0eMessengerQuery\x12\r\n\x05query\x18\x01 \x01(\t\"%\n\x11MessengerResponse\x12\x10\n\x08response\x18\x01 \x01(\t2L\n\x0fMessengerCaller\x12\x39\n\x10GetMessengerData\x12\x0f.MessengerQuery\x1a\x12.MessengerResponse\"\x00\x62\x06proto3')
)




_MESSENGERQUERY = _descriptor.Descriptor(
  name='MessengerQuery',
  full_name='MessengerQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='MessengerQuery.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=50,
)


_MESSENGERRESPONSE = _descriptor.Descriptor(
  name='MessengerResponse',
  full_name='MessengerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='MessengerResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['MessengerQuery'] = _MESSENGERQUERY
DESCRIPTOR.message_types_by_name['MessengerResponse'] = _MESSENGERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessengerQuery = _reflection.GeneratedProtocolMessageType('MessengerQuery', (_message.Message,), dict(
  DESCRIPTOR = _MESSENGERQUERY,
  __module__ = 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:MessengerQuery)
  ))
_sym_db.RegisterMessage(MessengerQuery)

MessengerResponse = _reflection.GeneratedProtocolMessageType('MessengerResponse', (_message.Message,), dict(
  DESCRIPTOR = _MESSENGERRESPONSE,
  __module__ = 'messenger_pb2'
  # @@protoc_insertion_point(class_scope:MessengerResponse)
  ))
_sym_db.RegisterMessage(MessengerResponse)



_MESSENGERCALLER = _descriptor.ServiceDescriptor(
  name='MessengerCaller',
  full_name='MessengerCaller',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=91,
  serialized_end=167,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMessengerData',
    full_name='MessengerCaller.GetMessengerData',
    index=0,
    containing_service=None,
    input_type=_MESSENGERQUERY,
    output_type=_MESSENGERRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MESSENGERCALLER)

DESCRIPTOR.services_by_name['MessengerCaller'] = _MESSENGERCALLER

# @@protoc_insertion_point(module_scope)
